//
//  PokemonData.swift
//  Pokedex
//
//  Created by Daniel No on 5/19/21.
//

import Foundation

public class PokemonData{
    var info =
        [
            ["name":"Bulbasaur",
             "id":1,
             "type":Type.grass.rawValue,
             "subtype":Type.poison.rawValue,
             "devolution":-1,
             "evolution":2
            ],
            ["name":"Ivysaur",
             "id":2,
             "type":Type.grass.rawValue,
             "subtype":Type.poison.rawValue,
             "devolution":1,
             "evolution":3
            ],
            ["name":"Venusaur",
             "id":3,
             "type":Type.grass.rawValue,
             "subtype":Type.poison.rawValue,
             "devolution":2,
             "evolution":-1
            ],
            ["name":"Charmander",
             "id":4,
             "type":Type.fire.rawValue,
             "subtype":Type.none.rawValue,
             "devolution":-1,
             "evolution":5
            ],
            ["name":"Charmeleon",
             "id":5,
             "type":Type.fire.rawValue,
             "subtype":Type.none.rawValue,
             "devolution":4,
             "evolution":6
            ],
            ["name":"Charizard",
             "id":6,
             "type":Type.fire.rawValue,
             "subtype":Type.flying.rawValue,
             "devolution":5,
             "evolution":-1
            ],
            ["name":"Squirtle",
             "id":7,
             "type":Type.water.rawValue,
             "subtype":Type.none.rawValue,
             "devolution":-1,
             "evolution":8
            ],
            ["name":"Wartortle",
             "id":8,
             "type":Type.water.rawValue,
             "subtype":Type.none.rawValue,
             "devolution":7,
             "evolution":9
            ],
            ["name":"Blastoise",
             "id":9,
             "type":Type.water.rawValue,
             "subtype":Type.none.rawValue,
             "devolution":8,
             "evolution":-1
            ],
            ["name":"Caterpie",
            "id":10,
            "type":Type.bug.rawValue,
            "subtype":Type.none.rawValue,
            "devolution":-1,
            "evolution":11
           ],
            ["name":"Metapod",
            "id":11,
            "type":Type.bug.rawValue,
            "subtype":Type.none.rawValue,
            "devolution":10,
            "evolution":12
           ],
            ["name":"Butterfree",
            "id":12,
            "type":Type.bug.rawValue,
            "subtype":Type.flying.rawValue,
            "devolution":11,
            "evolution":-1
           ],
            ["name":"Weedle",
            "id":13,
            "type":Type.bug.rawValue,
            "subtype":Type.poison.rawValue,
            "devolution":-1,
            "evolution":14
           ],
            ["name":"Kakuna",
            "id":14,
            "type":Type.bug.rawValue,
            "subtype":Type.poison.rawValue,
            "devolution":13,
            "evolution":15
           ],
            ["name":"Beedrill",
            "id":15,
            "type":Type.bug.rawValue,
            "subtype":Type.poison.rawValue,
            "devolution":14,
            "evolution":-1
           ],
            ["name":"Pidgey",
            "id":16,
            "type":Type.normal.rawValue,
            "subtype":Type.flying.rawValue,
            "devolution":-1,
            "evolution":17
           ],
            ["name":"Pidgeotto",
            "id":17,
            "type":Type.normal.rawValue,
            "subtype":Type.flying.rawValue,
            "devolution":16,
            "evolution":18
           ],
            ["name":"Pidgeot",
            "id":18,
            "type":Type.normal.rawValue,
            "subtype":Type.flying.rawValue,
            "devolution":17,
            "evolution":-1
           ],
            ["name":"Rattata",
            "id":19,
            "type":Type.normal.rawValue,
            "subtype":Type.none.rawValue,
            "devolution":-1,
            "evolution":20
           ],
            ["name":"Raticate",
            "id":20,
            "type":Type.normal.rawValue,
            "subtype":Type.none.rawValue,
            "devolution":19,
            "evolution":-1
           ],
            ["name":"Spearow",
            "id":21,
            "type":Type.normal.rawValue,
            "subtype":Type.flying.rawValue,
            "devolution":-1,
            "evolution":22
           ],
            ["name":"Fearow",
            "id":22,
            "type":Type.normal.rawValue,
            "subtype":Type.flying.rawValue,
            "devolution":21,
            "evolution":-1
           ],
            ["name":"Ekans",
            "id":23,
            "type":Type.poison.rawValue,
            "subtype":Type.none.rawValue,
            "devolution":-1,
            "evolution":24
           ],
            ["name":"Arbok",
            "id":24,
            "type":Type.poison.rawValue,
            "subtype":Type.none.rawValue,
            "devolution":23,
            "evolution":-1
           ],
            ["name":"Pikachu",
            "id":25,
            "type":Type.electric.rawValue,
            "subtype":Type.none.rawValue,
            "devolution":-1,
            "evolution":26
           ],
            ["name":"Raichu",
            "id":26,
            "type":Type.electric.rawValue,
            "subtype":Type.none.rawValue,
            "devolution":25,
            "evolution":-1
           ],

            ["name":"Machop",
            "id":66,
            "type":Type.fighting.rawValue,
            "subtype":Type.none.rawValue,
            "devolution":-1,
            "evolution":67
           ],
            ["name":"Machoke",
            "id":67,
            "type":Type.fighting.rawValue,
            "subtype":Type.none.rawValue,
            "devolution":66,
            "evolution":68
           ],
            ["name":"Machamp",
            "id":68,
            "type":Type.fighting.rawValue,
            "subtype":Type.none.rawValue,
            "devolution":67,
            "evolution":-1
           ],

            
            ["name":"Mewtwo",
            "id":150,
            "type":Type.psychic.rawValue,
            "subtype":Type.none.rawValue,
            "devolution":-1,
            "evolution":-1
           ],
            ["name":"Mew",
            "id":151,
            "type":Type.psychic.rawValue,
            "subtype":Type.none.rawValue,
            "devolution":-1,
            "evolution":-1
           ],

    
    
        ]
    
/*
     ["name":"",
     "id":,
     "type":Type..rawValue,
     "subtype":Type.none.rawValue,
     "devolution":,
     "evolution":
    ],
*/

    
    
}
